image: php:8.2

stages:
  - deploy

before_script:
  - apt-get update -y
  - apt-get install -y sshpass

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - sshpass -p $SSH_PASSWORD ssh -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        source ~/.bashrc &&
        php /home/u625132372/composer --version &&
        cd $REMOTE_DIR &&
        if [ ! -d .git ]; then
          git clone $GIT_REPO_URL .;
        else
          git fetch origin master &&
          git add . &&
          git commit -m 'Temporary commit for rebase' || echo 'No changes to commit' &&
          git rebase origin/master;
        fi &&
        php /home/u625132372/composer install &&
        npm install -g dotenv-cli &&
        cp .env.build .env &&
        npm install &&
        php artisan key:generate &&
        php artisan migrate:fresh --env=testing &&
        php artisan migrate --force &&
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan view:cache"
  only:
    - master
  environment:
    name: production
    url: http://gptchatroom.chang180backend.com
